/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopStoreSlugRouteImport } from './routes/shop.$storeSlug'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated.suppliers'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated.store'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated.sales'
import { Route as AuthenticatedRefundsRouteImport } from './routes/_authenticated.refunds'
import { Route as AuthenticatedQuickExpensesRouteImport } from './routes/_authenticated.quick-expenses'
import { Route as AuthenticatedPosOrdersRouteImport } from './routes/_authenticated.pos-orders'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated.pos'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated.payments'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated.invoices'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated.inventory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated.customers'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated.collections'
import { Route as AuthenticatedCashSessionsRouteImport } from './routes/_authenticated.cash-sessions'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated.bills'
import { Route as ShopStoreSlugIndexRouteImport } from './routes/shop.$storeSlug.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated.reports.index'
import { Route as ShopStoreSlugCheckoutRouteImport } from './routes/shop.$storeSlug.checkout'
import { Route as ShopStoreSlugCartRouteImport } from './routes/shop.$storeSlug.cart'
import { Route as ShopStoreSlugAccountRouteImport } from './routes/shop.$storeSlug.account'
import { Route as ApiStorefrontSetupRouteImport } from './routes/api.storefront.setup'
import { Route as ApiStorefrontProductRouteImport } from './routes/api.storefront.product'
import { Route as ApiStorefrontPreviewRouteImport } from './routes/api.storefront.preview'
import { Route as ApiStorefrontDesignRouteImport } from './routes/api.storefront.design'
import { Route as ApiStorefrontCheckoutContextRouteImport } from './routes/api.storefront.checkout-context'
import { Route as ApiStorefrontCheckoutRouteImport } from './routes/api.storefront.checkout'
import { Route as ApiStorefrontCatalogRouteImport } from './routes/api.storefront.catalog'
import { Route as ApiStorefrontAccountRouteImport } from './routes/api.storefront.account'
import { Route as ApiCommunicationsSendRouteImport } from './routes/api.communications.send'
import { Route as ApiCommunicationsRunScheduledRouteImport } from './routes/api.communications.run-scheduled'
import { Route as ApiCommunicationsRetryRouteImport } from './routes/api.communications.retry'
import { Route as ApiCommunicationsProcessQueueRouteImport } from './routes/api.communications.process-queue'
import { Route as ApiCommunicationsBatchSendRouteImport } from './routes/api.communications.batch-send'
import { Route as ApiCommunicationsBatchPreviewRouteImport } from './routes/api.communications.batch-preview'
import { Route as ApiCollectionsDashboardRouteImport } from './routes/api.collections.dashboard'
import { Route as AuthenticatedStoreSetupRouteImport } from './routes/_authenticated.store.setup'
import { Route as AuthenticatedStoreDesignRouteImport } from './routes/_authenticated.store.design'
import { Route as AuthenticatedStoreOrderIdRouteImport } from './routes/_authenticated.store.$orderId'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated.settings.users'
import { Route as AuthenticatedSettingsTaxRatesRouteImport } from './routes/_authenticated.settings.tax-rates'
import { Route as AuthenticatedSettingsModulesRouteImport } from './routes/_authenticated.settings.modules'
import { Route as AuthenticatedSettingsDocumentTemplatesRouteImport } from './routes/_authenticated.settings.document-templates'
import { Route as AuthenticatedSettingsCollectionsRouteImport } from './routes/_authenticated.settings.collections'
import { Route as AuthenticatedSettingsBranchesRouteImport } from './routes/_authenticated.settings.branches'
import { Route as AuthenticatedSalesOrderIdRouteImport } from './routes/_authenticated.sales.$orderId'
import { Route as AuthenticatedReportsTrialBalanceRouteImport } from './routes/_authenticated.reports.trial-balance'
import { Route as AuthenticatedReportsTaxRouteImport } from './routes/_authenticated.reports.tax'
import { Route as AuthenticatedReportsSalesRouteImport } from './routes/_authenticated.reports.sales'
import { Route as AuthenticatedReportsProfitLossRouteImport } from './routes/_authenticated.reports.profit-loss'
import { Route as AuthenticatedReportsLedgerRouteImport } from './routes/_authenticated.reports.ledger'
import { Route as AuthenticatedReportsCashFlowRouteImport } from './routes/_authenticated.reports.cash-flow'
import { Route as AuthenticatedReportsBalanceSheetRouteImport } from './routes/_authenticated.reports.balance-sheet'
import { Route as AuthenticatedRefundsCreditNoteIdRouteImport } from './routes/_authenticated.refunds.$creditNoteId'
import { Route as AuthenticatedQuickExpensesExpenseIdRouteImport } from './routes/_authenticated.quick-expenses.$expenseId'
import { Route as AuthenticatedPosOrdersOrderIdRouteImport } from './routes/_authenticated.pos-orders.$orderId'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated.invoices.$invoiceId'
import { Route as AuthenticatedInventoryProductIdRouteImport } from './routes/_authenticated.inventory.$productId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated.customers.$customerId'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated.bills.$billId'
import { Route as AuthenticatedAccountingControlsRouteImport } from './routes/_authenticated.accounting.controls'
import { Route as AuthenticatedAccountingCoaRouteImport } from './routes/_authenticated.accounting.coa'
import { Route as ShopStoreSlugProductProductKeyRouteImport } from './routes/shop.$storeSlug.product.$productKey'
import { Route as ShopStoreSlugOrderOrderIdRouteImport } from './routes/shop.$storeSlug.order.$orderId'
import { Route as ShopStoreSlugCategoryCategoryKeyRouteImport } from './routes/shop.$storeSlug.category.$categoryKey'
import { Route as ShopStoreSlugAccountAccessRouteImport } from './routes/shop.$storeSlug.account.access'
import { Route as ApiStorefrontAccountRetryPaymentRouteImport } from './routes/api.storefront.account.retry-payment'
import { Route as ApiStorefrontAccountPayInvoiceRouteImport } from './routes/api.storefront.account.pay-invoice'
import { Route as ApiStorefrontAccountOrderRouteImport } from './routes/api.storefront.account.order'
import { Route as ApiStorefrontAccountDocumentRouteImport } from './routes/api.storefront.account.document'
import { Route as ApiStorefrontAccountAccessRouteImport } from './routes/api.storefront.account.access'
import { Route as ApiDocumentsQuickExpenseIdRouteImport } from './routes/api.documents.quick-expense.$id'
import { Route as ApiDocumentsPosReceiptIdRouteImport } from './routes/api.documents.pos-receipt.$id'
import { Route as ApiDocumentsInvoiceIdRouteImport } from './routes/api.documents.invoice.$id'
import { Route as ApiDocumentsCustomerStatementCustomerIdRouteImport } from './routes/api.documents.customer-statement.$customerId'
import { Route as ApiDocumentsCreditNoteIdRouteImport } from './routes/api.documents.credit-note.$id'
import { Route as ApiDocumentsCashSessionIdRouteImport } from './routes/api.documents.cash-session.$id'
import { Route as ApiDocumentsBillIdRouteImport } from './routes/api.documents.bill.$id'
import { Route as ApiCommunicationsWebhooksResendRouteImport } from './routes/api.communications.webhooks.resend'
import { Route as ApiStorefrontPaymentsWebhooksStripeRouteImport } from './routes/api.storefront.payments.webhooks.stripe'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopStoreSlugRoute = ShopStoreSlugRouteImport.update({
  id: '/shop/$storeSlug',
  path: '/shop/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRefundsRoute = AuthenticatedRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuickExpensesRoute =
  AuthenticatedQuickExpensesRouteImport.update({
    id: '/quick-expenses',
    path: '/quick-expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPosOrdersRoute = AuthenticatedPosOrdersRouteImport.update({
  id: '/pos-orders',
  path: '/pos-orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCashSessionsRoute =
  AuthenticatedCashSessionsRouteImport.update({
    id: '/cash-sessions',
    path: '/cash-sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShopStoreSlugIndexRoute = ShopStoreSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopStoreSlugRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ShopStoreSlugCheckoutRoute = ShopStoreSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopStoreSlugRoute,
} as any)
const ShopStoreSlugCartRoute = ShopStoreSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopStoreSlugRoute,
} as any)
const ShopStoreSlugAccountRoute = ShopStoreSlugAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopStoreSlugRoute,
} as any)
const ApiStorefrontSetupRoute = ApiStorefrontSetupRouteImport.update({
  id: '/api/storefront/setup',
  path: '/api/storefront/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontProductRoute = ApiStorefrontProductRouteImport.update({
  id: '/api/storefront/product',
  path: '/api/storefront/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontPreviewRoute = ApiStorefrontPreviewRouteImport.update({
  id: '/api/storefront/preview',
  path: '/api/storefront/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontDesignRoute = ApiStorefrontDesignRouteImport.update({
  id: '/api/storefront/design',
  path: '/api/storefront/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontCheckoutContextRoute =
  ApiStorefrontCheckoutContextRouteImport.update({
    id: '/api/storefront/checkout-context',
    path: '/api/storefront/checkout-context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorefrontCheckoutRoute = ApiStorefrontCheckoutRouteImport.update({
  id: '/api/storefront/checkout',
  path: '/api/storefront/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontCatalogRoute = ApiStorefrontCatalogRouteImport.update({
  id: '/api/storefront/catalog',
  path: '/api/storefront/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontAccountRoute = ApiStorefrontAccountRouteImport.update({
  id: '/api/storefront/account',
  path: '/api/storefront/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunicationsSendRoute = ApiCommunicationsSendRouteImport.update({
  id: '/api/communications/send',
  path: '/api/communications/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunicationsRunScheduledRoute =
  ApiCommunicationsRunScheduledRouteImport.update({
    id: '/api/communications/run-scheduled',
    path: '/api/communications/run-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommunicationsRetryRoute = ApiCommunicationsRetryRouteImport.update({
  id: '/api/communications/retry',
  path: '/api/communications/retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunicationsProcessQueueRoute =
  ApiCommunicationsProcessQueueRouteImport.update({
    id: '/api/communications/process-queue',
    path: '/api/communications/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommunicationsBatchSendRoute =
  ApiCommunicationsBatchSendRouteImport.update({
    id: '/api/communications/batch-send',
    path: '/api/communications/batch-send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommunicationsBatchPreviewRoute =
  ApiCommunicationsBatchPreviewRouteImport.update({
    id: '/api/communications/batch-preview',
    path: '/api/communications/batch-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectionsDashboardRoute = ApiCollectionsDashboardRouteImport.update({
  id: '/api/collections/dashboard',
  path: '/api/collections/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreSetupRoute = AuthenticatedStoreSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedStoreRoute,
} as any)
const AuthenticatedStoreDesignRoute =
  AuthenticatedStoreDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedStoreRoute,
  } as any)
const AuthenticatedStoreOrderIdRoute =
  AuthenticatedStoreOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedStoreRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTaxRatesRoute =
  AuthenticatedSettingsTaxRatesRouteImport.update({
    id: '/tax-rates',
    path: '/tax-rates',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsModulesRoute =
  AuthenticatedSettingsModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDocumentTemplatesRoute =
  AuthenticatedSettingsDocumentTemplatesRouteImport.update({
    id: '/document-templates',
    path: '/document-templates',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCollectionsRoute =
  AuthenticatedSettingsCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBranchesRoute =
  AuthenticatedSettingsBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSalesOrderIdRoute =
  AuthenticatedSalesOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedSalesRoute,
  } as any)
const AuthenticatedReportsTrialBalanceRoute =
  AuthenticatedReportsTrialBalanceRouteImport.update({
    id: '/reports/trial-balance',
    path: '/reports/trial-balance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsTaxRoute = AuthenticatedReportsTaxRouteImport.update({
  id: '/reports/tax',
  path: '/reports/tax',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsSalesRoute =
  AuthenticatedReportsSalesRouteImport.update({
    id: '/reports/sales',
    path: '/reports/sales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsProfitLossRoute =
  AuthenticatedReportsProfitLossRouteImport.update({
    id: '/reports/profit-loss',
    path: '/reports/profit-loss',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsLedgerRoute =
  AuthenticatedReportsLedgerRouteImport.update({
    id: '/reports/ledger',
    path: '/reports/ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsCashFlowRoute =
  AuthenticatedReportsCashFlowRouteImport.update({
    id: '/reports/cash-flow',
    path: '/reports/cash-flow',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsBalanceSheetRoute =
  AuthenticatedReportsBalanceSheetRouteImport.update({
    id: '/reports/balance-sheet',
    path: '/reports/balance-sheet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRefundsCreditNoteIdRoute =
  AuthenticatedRefundsCreditNoteIdRouteImport.update({
    id: '/$creditNoteId',
    path: '/$creditNoteId',
    getParentRoute: () => AuthenticatedRefundsRoute,
  } as any)
const AuthenticatedQuickExpensesExpenseIdRoute =
  AuthenticatedQuickExpensesExpenseIdRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => AuthenticatedQuickExpensesRoute,
  } as any)
const AuthenticatedPosOrdersOrderIdRoute =
  AuthenticatedPosOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedPosOrdersRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInventoryProductIdRoute =
  AuthenticatedInventoryProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/$billId',
    path: '/$billId',
    getParentRoute: () => AuthenticatedBillsRoute,
  } as any)
const AuthenticatedAccountingControlsRoute =
  AuthenticatedAccountingControlsRouteImport.update({
    id: '/accounting/controls',
    path: '/accounting/controls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingCoaRoute =
  AuthenticatedAccountingCoaRouteImport.update({
    id: '/accounting/coa',
    path: '/accounting/coa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ShopStoreSlugProductProductKeyRoute =
  ShopStoreSlugProductProductKeyRouteImport.update({
    id: '/product/$productKey',
    path: '/product/$productKey',
    getParentRoute: () => ShopStoreSlugRoute,
  } as any)
const ShopStoreSlugOrderOrderIdRoute =
  ShopStoreSlugOrderOrderIdRouteImport.update({
    id: '/order/$orderId',
    path: '/order/$orderId',
    getParentRoute: () => ShopStoreSlugRoute,
  } as any)
const ShopStoreSlugCategoryCategoryKeyRoute =
  ShopStoreSlugCategoryCategoryKeyRouteImport.update({
    id: '/category/$categoryKey',
    path: '/category/$categoryKey',
    getParentRoute: () => ShopStoreSlugRoute,
  } as any)
const ShopStoreSlugAccountAccessRoute =
  ShopStoreSlugAccountAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => ShopStoreSlugAccountRoute,
  } as any)
const ApiStorefrontAccountRetryPaymentRoute =
  ApiStorefrontAccountRetryPaymentRouteImport.update({
    id: '/retry-payment',
    path: '/retry-payment',
    getParentRoute: () => ApiStorefrontAccountRoute,
  } as any)
const ApiStorefrontAccountPayInvoiceRoute =
  ApiStorefrontAccountPayInvoiceRouteImport.update({
    id: '/pay-invoice',
    path: '/pay-invoice',
    getParentRoute: () => ApiStorefrontAccountRoute,
  } as any)
const ApiStorefrontAccountOrderRoute =
  ApiStorefrontAccountOrderRouteImport.update({
    id: '/order',
    path: '/order',
    getParentRoute: () => ApiStorefrontAccountRoute,
  } as any)
const ApiStorefrontAccountDocumentRoute =
  ApiStorefrontAccountDocumentRouteImport.update({
    id: '/document',
    path: '/document',
    getParentRoute: () => ApiStorefrontAccountRoute,
  } as any)
const ApiStorefrontAccountAccessRoute =
  ApiStorefrontAccountAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => ApiStorefrontAccountRoute,
  } as any)
const ApiDocumentsQuickExpenseIdRoute =
  ApiDocumentsQuickExpenseIdRouteImport.update({
    id: '/api/documents/quick-expense/$id',
    path: '/api/documents/quick-expense/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsPosReceiptIdRoute =
  ApiDocumentsPosReceiptIdRouteImport.update({
    id: '/api/documents/pos-receipt/$id',
    path: '/api/documents/pos-receipt/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsInvoiceIdRoute = ApiDocumentsInvoiceIdRouteImport.update({
  id: '/api/documents/invoice/$id',
  path: '/api/documents/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsCustomerStatementCustomerIdRoute =
  ApiDocumentsCustomerStatementCustomerIdRouteImport.update({
    id: '/api/documents/customer-statement/$customerId',
    path: '/api/documents/customer-statement/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsCreditNoteIdRoute =
  ApiDocumentsCreditNoteIdRouteImport.update({
    id: '/api/documents/credit-note/$id',
    path: '/api/documents/credit-note/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsCashSessionIdRoute =
  ApiDocumentsCashSessionIdRouteImport.update({
    id: '/api/documents/cash-session/$id',
    path: '/api/documents/cash-session/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsBillIdRoute = ApiDocumentsBillIdRouteImport.update({
  id: '/api/documents/bill/$id',
  path: '/api/documents/bill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunicationsWebhooksResendRoute =
  ApiCommunicationsWebhooksResendRouteImport.update({
    id: '/api/communications/webhooks/resend',
    path: '/api/communications/webhooks/resend',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorefrontPaymentsWebhooksStripeRoute =
  ApiStorefrontPaymentsWebhooksStripeRouteImport.update({
    id: '/api/storefront/payments/webhooks/stripe',
    path: '/api/storefront/payments/webhooks/stripe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bills': typeof AuthenticatedBillsRouteWithChildren
  '/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pos-orders': typeof AuthenticatedPosOrdersRouteWithChildren
  '/quick-expenses': typeof AuthenticatedQuickExpensesRouteWithChildren
  '/refunds': typeof AuthenticatedRefundsRouteWithChildren
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/store': typeof AuthenticatedStoreRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/shop/$storeSlug': typeof ShopStoreSlugRouteWithChildren
  '/accounting/coa': typeof AuthenticatedAccountingCoaRoute
  '/accounting/controls': typeof AuthenticatedAccountingControlsRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/inventory/$productId': typeof AuthenticatedInventoryProductIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/pos-orders/$orderId': typeof AuthenticatedPosOrdersOrderIdRoute
  '/quick-expenses/$expenseId': typeof AuthenticatedQuickExpensesExpenseIdRoute
  '/refunds/$creditNoteId': typeof AuthenticatedRefundsCreditNoteIdRoute
  '/reports/balance-sheet': typeof AuthenticatedReportsBalanceSheetRoute
  '/reports/cash-flow': typeof AuthenticatedReportsCashFlowRoute
  '/reports/ledger': typeof AuthenticatedReportsLedgerRoute
  '/reports/profit-loss': typeof AuthenticatedReportsProfitLossRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/reports/tax': typeof AuthenticatedReportsTaxRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/settings/collections': typeof AuthenticatedSettingsCollectionsRoute
  '/settings/document-templates': typeof AuthenticatedSettingsDocumentTemplatesRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/store/$orderId': typeof AuthenticatedStoreOrderIdRoute
  '/store/design': typeof AuthenticatedStoreDesignRoute
  '/store/setup': typeof AuthenticatedStoreSetupRoute
  '/api/collections/dashboard': typeof ApiCollectionsDashboardRoute
  '/api/communications/batch-preview': typeof ApiCommunicationsBatchPreviewRoute
  '/api/communications/batch-send': typeof ApiCommunicationsBatchSendRoute
  '/api/communications/process-queue': typeof ApiCommunicationsProcessQueueRoute
  '/api/communications/retry': typeof ApiCommunicationsRetryRoute
  '/api/communications/run-scheduled': typeof ApiCommunicationsRunScheduledRoute
  '/api/communications/send': typeof ApiCommunicationsSendRoute
  '/api/storefront/account': typeof ApiStorefrontAccountRouteWithChildren
  '/api/storefront/catalog': typeof ApiStorefrontCatalogRoute
  '/api/storefront/checkout': typeof ApiStorefrontCheckoutRoute
  '/api/storefront/checkout-context': typeof ApiStorefrontCheckoutContextRoute
  '/api/storefront/design': typeof ApiStorefrontDesignRoute
  '/api/storefront/preview': typeof ApiStorefrontPreviewRoute
  '/api/storefront/product': typeof ApiStorefrontProductRoute
  '/api/storefront/setup': typeof ApiStorefrontSetupRoute
  '/shop/$storeSlug/account': typeof ShopStoreSlugAccountRouteWithChildren
  '/shop/$storeSlug/cart': typeof ShopStoreSlugCartRoute
  '/shop/$storeSlug/checkout': typeof ShopStoreSlugCheckoutRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shop/$storeSlug/': typeof ShopStoreSlugIndexRoute
  '/api/communications/webhooks/resend': typeof ApiCommunicationsWebhooksResendRoute
  '/api/documents/bill/$id': typeof ApiDocumentsBillIdRoute
  '/api/documents/cash-session/$id': typeof ApiDocumentsCashSessionIdRoute
  '/api/documents/credit-note/$id': typeof ApiDocumentsCreditNoteIdRoute
  '/api/documents/customer-statement/$customerId': typeof ApiDocumentsCustomerStatementCustomerIdRoute
  '/api/documents/invoice/$id': typeof ApiDocumentsInvoiceIdRoute
  '/api/documents/pos-receipt/$id': typeof ApiDocumentsPosReceiptIdRoute
  '/api/documents/quick-expense/$id': typeof ApiDocumentsQuickExpenseIdRoute
  '/api/storefront/account/access': typeof ApiStorefrontAccountAccessRoute
  '/api/storefront/account/document': typeof ApiStorefrontAccountDocumentRoute
  '/api/storefront/account/order': typeof ApiStorefrontAccountOrderRoute
  '/api/storefront/account/pay-invoice': typeof ApiStorefrontAccountPayInvoiceRoute
  '/api/storefront/account/retry-payment': typeof ApiStorefrontAccountRetryPaymentRoute
  '/shop/$storeSlug/account/access': typeof ShopStoreSlugAccountAccessRoute
  '/shop/$storeSlug/category/$categoryKey': typeof ShopStoreSlugCategoryCategoryKeyRoute
  '/shop/$storeSlug/order/$orderId': typeof ShopStoreSlugOrderOrderIdRoute
  '/shop/$storeSlug/product/$productKey': typeof ShopStoreSlugProductProductKeyRoute
  '/api/storefront/payments/webhooks/stripe': typeof ApiStorefrontPaymentsWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bills': typeof AuthenticatedBillsRouteWithChildren
  '/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pos-orders': typeof AuthenticatedPosOrdersRouteWithChildren
  '/quick-expenses': typeof AuthenticatedQuickExpensesRouteWithChildren
  '/refunds': typeof AuthenticatedRefundsRouteWithChildren
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/store': typeof AuthenticatedStoreRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/accounting/coa': typeof AuthenticatedAccountingCoaRoute
  '/accounting/controls': typeof AuthenticatedAccountingControlsRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/inventory/$productId': typeof AuthenticatedInventoryProductIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/pos-orders/$orderId': typeof AuthenticatedPosOrdersOrderIdRoute
  '/quick-expenses/$expenseId': typeof AuthenticatedQuickExpensesExpenseIdRoute
  '/refunds/$creditNoteId': typeof AuthenticatedRefundsCreditNoteIdRoute
  '/reports/balance-sheet': typeof AuthenticatedReportsBalanceSheetRoute
  '/reports/cash-flow': typeof AuthenticatedReportsCashFlowRoute
  '/reports/ledger': typeof AuthenticatedReportsLedgerRoute
  '/reports/profit-loss': typeof AuthenticatedReportsProfitLossRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/reports/tax': typeof AuthenticatedReportsTaxRoute
  '/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/settings/collections': typeof AuthenticatedSettingsCollectionsRoute
  '/settings/document-templates': typeof AuthenticatedSettingsDocumentTemplatesRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/store/$orderId': typeof AuthenticatedStoreOrderIdRoute
  '/store/design': typeof AuthenticatedStoreDesignRoute
  '/store/setup': typeof AuthenticatedStoreSetupRoute
  '/api/collections/dashboard': typeof ApiCollectionsDashboardRoute
  '/api/communications/batch-preview': typeof ApiCommunicationsBatchPreviewRoute
  '/api/communications/batch-send': typeof ApiCommunicationsBatchSendRoute
  '/api/communications/process-queue': typeof ApiCommunicationsProcessQueueRoute
  '/api/communications/retry': typeof ApiCommunicationsRetryRoute
  '/api/communications/run-scheduled': typeof ApiCommunicationsRunScheduledRoute
  '/api/communications/send': typeof ApiCommunicationsSendRoute
  '/api/storefront/account': typeof ApiStorefrontAccountRouteWithChildren
  '/api/storefront/catalog': typeof ApiStorefrontCatalogRoute
  '/api/storefront/checkout': typeof ApiStorefrontCheckoutRoute
  '/api/storefront/checkout-context': typeof ApiStorefrontCheckoutContextRoute
  '/api/storefront/design': typeof ApiStorefrontDesignRoute
  '/api/storefront/preview': typeof ApiStorefrontPreviewRoute
  '/api/storefront/product': typeof ApiStorefrontProductRoute
  '/api/storefront/setup': typeof ApiStorefrontSetupRoute
  '/shop/$storeSlug/account': typeof ShopStoreSlugAccountRouteWithChildren
  '/shop/$storeSlug/cart': typeof ShopStoreSlugCartRoute
  '/shop/$storeSlug/checkout': typeof ShopStoreSlugCheckoutRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/shop/$storeSlug': typeof ShopStoreSlugIndexRoute
  '/api/communications/webhooks/resend': typeof ApiCommunicationsWebhooksResendRoute
  '/api/documents/bill/$id': typeof ApiDocumentsBillIdRoute
  '/api/documents/cash-session/$id': typeof ApiDocumentsCashSessionIdRoute
  '/api/documents/credit-note/$id': typeof ApiDocumentsCreditNoteIdRoute
  '/api/documents/customer-statement/$customerId': typeof ApiDocumentsCustomerStatementCustomerIdRoute
  '/api/documents/invoice/$id': typeof ApiDocumentsInvoiceIdRoute
  '/api/documents/pos-receipt/$id': typeof ApiDocumentsPosReceiptIdRoute
  '/api/documents/quick-expense/$id': typeof ApiDocumentsQuickExpenseIdRoute
  '/api/storefront/account/access': typeof ApiStorefrontAccountAccessRoute
  '/api/storefront/account/document': typeof ApiStorefrontAccountDocumentRoute
  '/api/storefront/account/order': typeof ApiStorefrontAccountOrderRoute
  '/api/storefront/account/pay-invoice': typeof ApiStorefrontAccountPayInvoiceRoute
  '/api/storefront/account/retry-payment': typeof ApiStorefrontAccountRetryPaymentRoute
  '/shop/$storeSlug/account/access': typeof ShopStoreSlugAccountAccessRoute
  '/shop/$storeSlug/category/$categoryKey': typeof ShopStoreSlugCategoryCategoryKeyRoute
  '/shop/$storeSlug/order/$orderId': typeof ShopStoreSlugOrderOrderIdRoute
  '/shop/$storeSlug/product/$productKey': typeof ShopStoreSlugProductProductKeyRoute
  '/api/storefront/payments/webhooks/stripe': typeof ApiStorefrontPaymentsWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRouteWithChildren
  '/_authenticated/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/pos-orders': typeof AuthenticatedPosOrdersRouteWithChildren
  '/_authenticated/quick-expenses': typeof AuthenticatedQuickExpensesRouteWithChildren
  '/_authenticated/refunds': typeof AuthenticatedRefundsRouteWithChildren
  '/_authenticated/sales': typeof AuthenticatedSalesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/store': typeof AuthenticatedStoreRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/shop/$storeSlug': typeof ShopStoreSlugRouteWithChildren
  '/_authenticated/accounting/coa': typeof AuthenticatedAccountingCoaRoute
  '/_authenticated/accounting/controls': typeof AuthenticatedAccountingControlsRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/inventory/$productId': typeof AuthenticatedInventoryProductIdRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/pos-orders/$orderId': typeof AuthenticatedPosOrdersOrderIdRoute
  '/_authenticated/quick-expenses/$expenseId': typeof AuthenticatedQuickExpensesExpenseIdRoute
  '/_authenticated/refunds/$creditNoteId': typeof AuthenticatedRefundsCreditNoteIdRoute
  '/_authenticated/reports/balance-sheet': typeof AuthenticatedReportsBalanceSheetRoute
  '/_authenticated/reports/cash-flow': typeof AuthenticatedReportsCashFlowRoute
  '/_authenticated/reports/ledger': typeof AuthenticatedReportsLedgerRoute
  '/_authenticated/reports/profit-loss': typeof AuthenticatedReportsProfitLossRoute
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/_authenticated/reports/tax': typeof AuthenticatedReportsTaxRoute
  '/_authenticated/reports/trial-balance': typeof AuthenticatedReportsTrialBalanceRoute
  '/_authenticated/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/_authenticated/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/_authenticated/settings/collections': typeof AuthenticatedSettingsCollectionsRoute
  '/_authenticated/settings/document-templates': typeof AuthenticatedSettingsDocumentTemplatesRoute
  '/_authenticated/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/_authenticated/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/store/$orderId': typeof AuthenticatedStoreOrderIdRoute
  '/_authenticated/store/design': typeof AuthenticatedStoreDesignRoute
  '/_authenticated/store/setup': typeof AuthenticatedStoreSetupRoute
  '/api/collections/dashboard': typeof ApiCollectionsDashboardRoute
  '/api/communications/batch-preview': typeof ApiCommunicationsBatchPreviewRoute
  '/api/communications/batch-send': typeof ApiCommunicationsBatchSendRoute
  '/api/communications/process-queue': typeof ApiCommunicationsProcessQueueRoute
  '/api/communications/retry': typeof ApiCommunicationsRetryRoute
  '/api/communications/run-scheduled': typeof ApiCommunicationsRunScheduledRoute
  '/api/communications/send': typeof ApiCommunicationsSendRoute
  '/api/storefront/account': typeof ApiStorefrontAccountRouteWithChildren
  '/api/storefront/catalog': typeof ApiStorefrontCatalogRoute
  '/api/storefront/checkout': typeof ApiStorefrontCheckoutRoute
  '/api/storefront/checkout-context': typeof ApiStorefrontCheckoutContextRoute
  '/api/storefront/design': typeof ApiStorefrontDesignRoute
  '/api/storefront/preview': typeof ApiStorefrontPreviewRoute
  '/api/storefront/product': typeof ApiStorefrontProductRoute
  '/api/storefront/setup': typeof ApiStorefrontSetupRoute
  '/shop/$storeSlug/account': typeof ShopStoreSlugAccountRouteWithChildren
  '/shop/$storeSlug/cart': typeof ShopStoreSlugCartRoute
  '/shop/$storeSlug/checkout': typeof ShopStoreSlugCheckoutRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shop/$storeSlug/': typeof ShopStoreSlugIndexRoute
  '/api/communications/webhooks/resend': typeof ApiCommunicationsWebhooksResendRoute
  '/api/documents/bill/$id': typeof ApiDocumentsBillIdRoute
  '/api/documents/cash-session/$id': typeof ApiDocumentsCashSessionIdRoute
  '/api/documents/credit-note/$id': typeof ApiDocumentsCreditNoteIdRoute
  '/api/documents/customer-statement/$customerId': typeof ApiDocumentsCustomerStatementCustomerIdRoute
  '/api/documents/invoice/$id': typeof ApiDocumentsInvoiceIdRoute
  '/api/documents/pos-receipt/$id': typeof ApiDocumentsPosReceiptIdRoute
  '/api/documents/quick-expense/$id': typeof ApiDocumentsQuickExpenseIdRoute
  '/api/storefront/account/access': typeof ApiStorefrontAccountAccessRoute
  '/api/storefront/account/document': typeof ApiStorefrontAccountDocumentRoute
  '/api/storefront/account/order': typeof ApiStorefrontAccountOrderRoute
  '/api/storefront/account/pay-invoice': typeof ApiStorefrontAccountPayInvoiceRoute
  '/api/storefront/account/retry-payment': typeof ApiStorefrontAccountRetryPaymentRoute
  '/shop/$storeSlug/account/access': typeof ShopStoreSlugAccountAccessRoute
  '/shop/$storeSlug/category/$categoryKey': typeof ShopStoreSlugCategoryCategoryKeyRoute
  '/shop/$storeSlug/order/$orderId': typeof ShopStoreSlugOrderOrderIdRoute
  '/shop/$storeSlug/product/$productKey': typeof ShopStoreSlugProductProductKeyRoute
  '/api/storefront/payments/webhooks/stripe': typeof ApiStorefrontPaymentsWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/bills'
    | '/cash-sessions'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/invoices'
    | '/payments'
    | '/pos'
    | '/pos-orders'
    | '/quick-expenses'
    | '/refunds'
    | '/sales'
    | '/settings'
    | '/store'
    | '/suppliers'
    | '/shop/$storeSlug'
    | '/accounting/coa'
    | '/accounting/controls'
    | '/bills/$billId'
    | '/customers/$customerId'
    | '/inventory/$productId'
    | '/invoices/$invoiceId'
    | '/pos-orders/$orderId'
    | '/quick-expenses/$expenseId'
    | '/refunds/$creditNoteId'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/ledger'
    | '/reports/profit-loss'
    | '/reports/sales'
    | '/reports/tax'
    | '/reports/trial-balance'
    | '/sales/$orderId'
    | '/settings/branches'
    | '/settings/collections'
    | '/settings/document-templates'
    | '/settings/modules'
    | '/settings/tax-rates'
    | '/settings/users'
    | '/store/$orderId'
    | '/store/design'
    | '/store/setup'
    | '/api/collections/dashboard'
    | '/api/communications/batch-preview'
    | '/api/communications/batch-send'
    | '/api/communications/process-queue'
    | '/api/communications/retry'
    | '/api/communications/run-scheduled'
    | '/api/communications/send'
    | '/api/storefront/account'
    | '/api/storefront/catalog'
    | '/api/storefront/checkout'
    | '/api/storefront/checkout-context'
    | '/api/storefront/design'
    | '/api/storefront/preview'
    | '/api/storefront/product'
    | '/api/storefront/setup'
    | '/shop/$storeSlug/account'
    | '/shop/$storeSlug/cart'
    | '/shop/$storeSlug/checkout'
    | '/reports/'
    | '/settings/'
    | '/shop/$storeSlug/'
    | '/api/communications/webhooks/resend'
    | '/api/documents/bill/$id'
    | '/api/documents/cash-session/$id'
    | '/api/documents/credit-note/$id'
    | '/api/documents/customer-statement/$customerId'
    | '/api/documents/invoice/$id'
    | '/api/documents/pos-receipt/$id'
    | '/api/documents/quick-expense/$id'
    | '/api/storefront/account/access'
    | '/api/storefront/account/document'
    | '/api/storefront/account/order'
    | '/api/storefront/account/pay-invoice'
    | '/api/storefront/account/retry-payment'
    | '/shop/$storeSlug/account/access'
    | '/shop/$storeSlug/category/$categoryKey'
    | '/shop/$storeSlug/order/$orderId'
    | '/shop/$storeSlug/product/$productKey'
    | '/api/storefront/payments/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/bills'
    | '/cash-sessions'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/invoices'
    | '/payments'
    | '/pos'
    | '/pos-orders'
    | '/quick-expenses'
    | '/refunds'
    | '/sales'
    | '/store'
    | '/suppliers'
    | '/accounting/coa'
    | '/accounting/controls'
    | '/bills/$billId'
    | '/customers/$customerId'
    | '/inventory/$productId'
    | '/invoices/$invoiceId'
    | '/pos-orders/$orderId'
    | '/quick-expenses/$expenseId'
    | '/refunds/$creditNoteId'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/ledger'
    | '/reports/profit-loss'
    | '/reports/sales'
    | '/reports/tax'
    | '/reports/trial-balance'
    | '/sales/$orderId'
    | '/settings/branches'
    | '/settings/collections'
    | '/settings/document-templates'
    | '/settings/modules'
    | '/settings/tax-rates'
    | '/settings/users'
    | '/store/$orderId'
    | '/store/design'
    | '/store/setup'
    | '/api/collections/dashboard'
    | '/api/communications/batch-preview'
    | '/api/communications/batch-send'
    | '/api/communications/process-queue'
    | '/api/communications/retry'
    | '/api/communications/run-scheduled'
    | '/api/communications/send'
    | '/api/storefront/account'
    | '/api/storefront/catalog'
    | '/api/storefront/checkout'
    | '/api/storefront/checkout-context'
    | '/api/storefront/design'
    | '/api/storefront/preview'
    | '/api/storefront/product'
    | '/api/storefront/setup'
    | '/shop/$storeSlug/account'
    | '/shop/$storeSlug/cart'
    | '/shop/$storeSlug/checkout'
    | '/reports'
    | '/settings'
    | '/shop/$storeSlug'
    | '/api/communications/webhooks/resend'
    | '/api/documents/bill/$id'
    | '/api/documents/cash-session/$id'
    | '/api/documents/credit-note/$id'
    | '/api/documents/customer-statement/$customerId'
    | '/api/documents/invoice/$id'
    | '/api/documents/pos-receipt/$id'
    | '/api/documents/quick-expense/$id'
    | '/api/storefront/account/access'
    | '/api/storefront/account/document'
    | '/api/storefront/account/order'
    | '/api/storefront/account/pay-invoice'
    | '/api/storefront/account/retry-payment'
    | '/shop/$storeSlug/account/access'
    | '/shop/$storeSlug/category/$categoryKey'
    | '/shop/$storeSlug/order/$orderId'
    | '/shop/$storeSlug/product/$productKey'
    | '/api/storefront/payments/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/bills'
    | '/_authenticated/cash-sessions'
    | '/_authenticated/collections'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/payments'
    | '/_authenticated/pos'
    | '/_authenticated/pos-orders'
    | '/_authenticated/quick-expenses'
    | '/_authenticated/refunds'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/store'
    | '/_authenticated/suppliers'
    | '/shop/$storeSlug'
    | '/_authenticated/accounting/coa'
    | '/_authenticated/accounting/controls'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/inventory/$productId'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/pos-orders/$orderId'
    | '/_authenticated/quick-expenses/$expenseId'
    | '/_authenticated/refunds/$creditNoteId'
    | '/_authenticated/reports/balance-sheet'
    | '/_authenticated/reports/cash-flow'
    | '/_authenticated/reports/ledger'
    | '/_authenticated/reports/profit-loss'
    | '/_authenticated/reports/sales'
    | '/_authenticated/reports/tax'
    | '/_authenticated/reports/trial-balance'
    | '/_authenticated/sales/$orderId'
    | '/_authenticated/settings/branches'
    | '/_authenticated/settings/collections'
    | '/_authenticated/settings/document-templates'
    | '/_authenticated/settings/modules'
    | '/_authenticated/settings/tax-rates'
    | '/_authenticated/settings/users'
    | '/_authenticated/store/$orderId'
    | '/_authenticated/store/design'
    | '/_authenticated/store/setup'
    | '/api/collections/dashboard'
    | '/api/communications/batch-preview'
    | '/api/communications/batch-send'
    | '/api/communications/process-queue'
    | '/api/communications/retry'
    | '/api/communications/run-scheduled'
    | '/api/communications/send'
    | '/api/storefront/account'
    | '/api/storefront/catalog'
    | '/api/storefront/checkout'
    | '/api/storefront/checkout-context'
    | '/api/storefront/design'
    | '/api/storefront/preview'
    | '/api/storefront/product'
    | '/api/storefront/setup'
    | '/shop/$storeSlug/account'
    | '/shop/$storeSlug/cart'
    | '/shop/$storeSlug/checkout'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/shop/$storeSlug/'
    | '/api/communications/webhooks/resend'
    | '/api/documents/bill/$id'
    | '/api/documents/cash-session/$id'
    | '/api/documents/credit-note/$id'
    | '/api/documents/customer-statement/$customerId'
    | '/api/documents/invoice/$id'
    | '/api/documents/pos-receipt/$id'
    | '/api/documents/quick-expense/$id'
    | '/api/storefront/account/access'
    | '/api/storefront/account/document'
    | '/api/storefront/account/order'
    | '/api/storefront/account/pay-invoice'
    | '/api/storefront/account/retry-payment'
    | '/shop/$storeSlug/account/access'
    | '/shop/$storeSlug/category/$categoryKey'
    | '/shop/$storeSlug/order/$orderId'
    | '/shop/$storeSlug/product/$productKey'
    | '/api/storefront/payments/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ShopStoreSlugRoute: typeof ShopStoreSlugRouteWithChildren
  ApiCollectionsDashboardRoute: typeof ApiCollectionsDashboardRoute
  ApiCommunicationsBatchPreviewRoute: typeof ApiCommunicationsBatchPreviewRoute
  ApiCommunicationsBatchSendRoute: typeof ApiCommunicationsBatchSendRoute
  ApiCommunicationsProcessQueueRoute: typeof ApiCommunicationsProcessQueueRoute
  ApiCommunicationsRetryRoute: typeof ApiCommunicationsRetryRoute
  ApiCommunicationsRunScheduledRoute: typeof ApiCommunicationsRunScheduledRoute
  ApiCommunicationsSendRoute: typeof ApiCommunicationsSendRoute
  ApiStorefrontAccountRoute: typeof ApiStorefrontAccountRouteWithChildren
  ApiStorefrontCatalogRoute: typeof ApiStorefrontCatalogRoute
  ApiStorefrontCheckoutRoute: typeof ApiStorefrontCheckoutRoute
  ApiStorefrontCheckoutContextRoute: typeof ApiStorefrontCheckoutContextRoute
  ApiStorefrontDesignRoute: typeof ApiStorefrontDesignRoute
  ApiStorefrontPreviewRoute: typeof ApiStorefrontPreviewRoute
  ApiStorefrontProductRoute: typeof ApiStorefrontProductRoute
  ApiStorefrontSetupRoute: typeof ApiStorefrontSetupRoute
  ApiCommunicationsWebhooksResendRoute: typeof ApiCommunicationsWebhooksResendRoute
  ApiDocumentsBillIdRoute: typeof ApiDocumentsBillIdRoute
  ApiDocumentsCashSessionIdRoute: typeof ApiDocumentsCashSessionIdRoute
  ApiDocumentsCreditNoteIdRoute: typeof ApiDocumentsCreditNoteIdRoute
  ApiDocumentsCustomerStatementCustomerIdRoute: typeof ApiDocumentsCustomerStatementCustomerIdRoute
  ApiDocumentsInvoiceIdRoute: typeof ApiDocumentsInvoiceIdRoute
  ApiDocumentsPosReceiptIdRoute: typeof ApiDocumentsPosReceiptIdRoute
  ApiDocumentsQuickExpenseIdRoute: typeof ApiDocumentsQuickExpenseIdRoute
  ApiStorefrontPaymentsWebhooksStripeRoute: typeof ApiStorefrontPaymentsWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$storeSlug': {
      id: '/shop/$storeSlug'
      path: '/shop/$storeSlug'
      fullPath: '/shop/$storeSlug'
      preLoaderRoute: typeof ShopStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refunds': {
      id: '/_authenticated/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof AuthenticatedRefundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quick-expenses': {
      id: '/_authenticated/quick-expenses'
      path: '/quick-expenses'
      fullPath: '/quick-expenses'
      preLoaderRoute: typeof AuthenticatedQuickExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos-orders': {
      id: '/_authenticated/pos-orders'
      path: '/pos-orders'
      fullPath: '/pos-orders'
      preLoaderRoute: typeof AuthenticatedPosOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cash-sessions': {
      id: '/_authenticated/cash-sessions'
      path: '/cash-sessions'
      fullPath: '/cash-sessions'
      preLoaderRoute: typeof AuthenticatedCashSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shop/$storeSlug/': {
      id: '/shop/$storeSlug/'
      path: '/'
      fullPath: '/shop/$storeSlug/'
      preLoaderRoute: typeof ShopStoreSlugIndexRouteImport
      parentRoute: typeof ShopStoreSlugRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shop/$storeSlug/checkout': {
      id: '/shop/$storeSlug/checkout'
      path: '/checkout'
      fullPath: '/shop/$storeSlug/checkout'
      preLoaderRoute: typeof ShopStoreSlugCheckoutRouteImport
      parentRoute: typeof ShopStoreSlugRoute
    }
    '/shop/$storeSlug/cart': {
      id: '/shop/$storeSlug/cart'
      path: '/cart'
      fullPath: '/shop/$storeSlug/cart'
      preLoaderRoute: typeof ShopStoreSlugCartRouteImport
      parentRoute: typeof ShopStoreSlugRoute
    }
    '/shop/$storeSlug/account': {
      id: '/shop/$storeSlug/account'
      path: '/account'
      fullPath: '/shop/$storeSlug/account'
      preLoaderRoute: typeof ShopStoreSlugAccountRouteImport
      parentRoute: typeof ShopStoreSlugRoute
    }
    '/api/storefront/setup': {
      id: '/api/storefront/setup'
      path: '/api/storefront/setup'
      fullPath: '/api/storefront/setup'
      preLoaderRoute: typeof ApiStorefrontSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront/product': {
      id: '/api/storefront/product'
      path: '/api/storefront/product'
      fullPath: '/api/storefront/product'
      preLoaderRoute: typeof ApiStorefrontProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront/preview': {
      id: '/api/storefront/preview'
      path: '/api/storefront/preview'
      fullPath: '/api/storefront/preview'
      preLoaderRoute: typeof ApiStorefrontPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront/design': {
      id: '/api/storefront/design'
      path: '/api/storefront/design'
      fullPath: '/api/storefront/design'
      preLoaderRoute: typeof ApiStorefrontDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront/checkout-context': {
      id: '/api/storefront/checkout-context'
      path: '/api/storefront/checkout-context'
      fullPath: '/api/storefront/checkout-context'
      preLoaderRoute: typeof ApiStorefrontCheckoutContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront/checkout': {
      id: '/api/storefront/checkout'
      path: '/api/storefront/checkout'
      fullPath: '/api/storefront/checkout'
      preLoaderRoute: typeof ApiStorefrontCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront/catalog': {
      id: '/api/storefront/catalog'
      path: '/api/storefront/catalog'
      fullPath: '/api/storefront/catalog'
      preLoaderRoute: typeof ApiStorefrontCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront/account': {
      id: '/api/storefront/account'
      path: '/api/storefront/account'
      fullPath: '/api/storefront/account'
      preLoaderRoute: typeof ApiStorefrontAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications/send': {
      id: '/api/communications/send'
      path: '/api/communications/send'
      fullPath: '/api/communications/send'
      preLoaderRoute: typeof ApiCommunicationsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications/run-scheduled': {
      id: '/api/communications/run-scheduled'
      path: '/api/communications/run-scheduled'
      fullPath: '/api/communications/run-scheduled'
      preLoaderRoute: typeof ApiCommunicationsRunScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications/retry': {
      id: '/api/communications/retry'
      path: '/api/communications/retry'
      fullPath: '/api/communications/retry'
      preLoaderRoute: typeof ApiCommunicationsRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications/process-queue': {
      id: '/api/communications/process-queue'
      path: '/api/communications/process-queue'
      fullPath: '/api/communications/process-queue'
      preLoaderRoute: typeof ApiCommunicationsProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications/batch-send': {
      id: '/api/communications/batch-send'
      path: '/api/communications/batch-send'
      fullPath: '/api/communications/batch-send'
      preLoaderRoute: typeof ApiCommunicationsBatchSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications/batch-preview': {
      id: '/api/communications/batch-preview'
      path: '/api/communications/batch-preview'
      fullPath: '/api/communications/batch-preview'
      preLoaderRoute: typeof ApiCommunicationsBatchPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections/dashboard': {
      id: '/api/collections/dashboard'
      path: '/api/collections/dashboard'
      fullPath: '/api/collections/dashboard'
      preLoaderRoute: typeof ApiCollectionsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store/setup': {
      id: '/_authenticated/store/setup'
      path: '/setup'
      fullPath: '/store/setup'
      preLoaderRoute: typeof AuthenticatedStoreSetupRouteImport
      parentRoute: typeof AuthenticatedStoreRoute
    }
    '/_authenticated/store/design': {
      id: '/_authenticated/store/design'
      path: '/design'
      fullPath: '/store/design'
      preLoaderRoute: typeof AuthenticatedStoreDesignRouteImport
      parentRoute: typeof AuthenticatedStoreRoute
    }
    '/_authenticated/store/$orderId': {
      id: '/_authenticated/store/$orderId'
      path: '/$orderId'
      fullPath: '/store/$orderId'
      preLoaderRoute: typeof AuthenticatedStoreOrderIdRouteImport
      parentRoute: typeof AuthenticatedStoreRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/tax-rates': {
      id: '/_authenticated/settings/tax-rates'
      path: '/tax-rates'
      fullPath: '/settings/tax-rates'
      preLoaderRoute: typeof AuthenticatedSettingsTaxRatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/modules': {
      id: '/_authenticated/settings/modules'
      path: '/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AuthenticatedSettingsModulesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/document-templates': {
      id: '/_authenticated/settings/document-templates'
      path: '/document-templates'
      fullPath: '/settings/document-templates'
      preLoaderRoute: typeof AuthenticatedSettingsDocumentTemplatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/collections': {
      id: '/_authenticated/settings/collections'
      path: '/collections'
      fullPath: '/settings/collections'
      preLoaderRoute: typeof AuthenticatedSettingsCollectionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/branches': {
      id: '/_authenticated/settings/branches'
      path: '/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof AuthenticatedSettingsBranchesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/sales/$orderId': {
      id: '/_authenticated/sales/$orderId'
      path: '/$orderId'
      fullPath: '/sales/$orderId'
      preLoaderRoute: typeof AuthenticatedSalesOrderIdRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/reports/trial-balance': {
      id: '/_authenticated/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AuthenticatedReportsTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/tax': {
      id: '/_authenticated/reports/tax'
      path: '/reports/tax'
      fullPath: '/reports/tax'
      preLoaderRoute: typeof AuthenticatedReportsTaxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/profit-loss': {
      id: '/_authenticated/reports/profit-loss'
      path: '/reports/profit-loss'
      fullPath: '/reports/profit-loss'
      preLoaderRoute: typeof AuthenticatedReportsProfitLossRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/ledger': {
      id: '/_authenticated/reports/ledger'
      path: '/reports/ledger'
      fullPath: '/reports/ledger'
      preLoaderRoute: typeof AuthenticatedReportsLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/cash-flow': {
      id: '/_authenticated/reports/cash-flow'
      path: '/reports/cash-flow'
      fullPath: '/reports/cash-flow'
      preLoaderRoute: typeof AuthenticatedReportsCashFlowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/balance-sheet': {
      id: '/_authenticated/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AuthenticatedReportsBalanceSheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refunds/$creditNoteId': {
      id: '/_authenticated/refunds/$creditNoteId'
      path: '/$creditNoteId'
      fullPath: '/refunds/$creditNoteId'
      preLoaderRoute: typeof AuthenticatedRefundsCreditNoteIdRouteImport
      parentRoute: typeof AuthenticatedRefundsRoute
    }
    '/_authenticated/quick-expenses/$expenseId': {
      id: '/_authenticated/quick-expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/quick-expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedQuickExpensesExpenseIdRouteImport
      parentRoute: typeof AuthenticatedQuickExpensesRoute
    }
    '/_authenticated/pos-orders/$orderId': {
      id: '/_authenticated/pos-orders/$orderId'
      path: '/$orderId'
      fullPath: '/pos-orders/$orderId'
      preLoaderRoute: typeof AuthenticatedPosOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedPosOrdersRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/inventory/$productId': {
      id: '/_authenticated/inventory/$productId'
      path: '/$productId'
      fullPath: '/inventory/$productId'
      preLoaderRoute: typeof AuthenticatedInventoryProductIdRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedBillsRoute
    }
    '/_authenticated/accounting/controls': {
      id: '/_authenticated/accounting/controls'
      path: '/accounting/controls'
      fullPath: '/accounting/controls'
      preLoaderRoute: typeof AuthenticatedAccountingControlsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/coa': {
      id: '/_authenticated/accounting/coa'
      path: '/accounting/coa'
      fullPath: '/accounting/coa'
      preLoaderRoute: typeof AuthenticatedAccountingCoaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shop/$storeSlug/product/$productKey': {
      id: '/shop/$storeSlug/product/$productKey'
      path: '/product/$productKey'
      fullPath: '/shop/$storeSlug/product/$productKey'
      preLoaderRoute: typeof ShopStoreSlugProductProductKeyRouteImport
      parentRoute: typeof ShopStoreSlugRoute
    }
    '/shop/$storeSlug/order/$orderId': {
      id: '/shop/$storeSlug/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/shop/$storeSlug/order/$orderId'
      preLoaderRoute: typeof ShopStoreSlugOrderOrderIdRouteImport
      parentRoute: typeof ShopStoreSlugRoute
    }
    '/shop/$storeSlug/category/$categoryKey': {
      id: '/shop/$storeSlug/category/$categoryKey'
      path: '/category/$categoryKey'
      fullPath: '/shop/$storeSlug/category/$categoryKey'
      preLoaderRoute: typeof ShopStoreSlugCategoryCategoryKeyRouteImport
      parentRoute: typeof ShopStoreSlugRoute
    }
    '/shop/$storeSlug/account/access': {
      id: '/shop/$storeSlug/account/access'
      path: '/access'
      fullPath: '/shop/$storeSlug/account/access'
      preLoaderRoute: typeof ShopStoreSlugAccountAccessRouteImport
      parentRoute: typeof ShopStoreSlugAccountRoute
    }
    '/api/storefront/account/retry-payment': {
      id: '/api/storefront/account/retry-payment'
      path: '/retry-payment'
      fullPath: '/api/storefront/account/retry-payment'
      preLoaderRoute: typeof ApiStorefrontAccountRetryPaymentRouteImport
      parentRoute: typeof ApiStorefrontAccountRoute
    }
    '/api/storefront/account/pay-invoice': {
      id: '/api/storefront/account/pay-invoice'
      path: '/pay-invoice'
      fullPath: '/api/storefront/account/pay-invoice'
      preLoaderRoute: typeof ApiStorefrontAccountPayInvoiceRouteImport
      parentRoute: typeof ApiStorefrontAccountRoute
    }
    '/api/storefront/account/order': {
      id: '/api/storefront/account/order'
      path: '/order'
      fullPath: '/api/storefront/account/order'
      preLoaderRoute: typeof ApiStorefrontAccountOrderRouteImport
      parentRoute: typeof ApiStorefrontAccountRoute
    }
    '/api/storefront/account/document': {
      id: '/api/storefront/account/document'
      path: '/document'
      fullPath: '/api/storefront/account/document'
      preLoaderRoute: typeof ApiStorefrontAccountDocumentRouteImport
      parentRoute: typeof ApiStorefrontAccountRoute
    }
    '/api/storefront/account/access': {
      id: '/api/storefront/account/access'
      path: '/access'
      fullPath: '/api/storefront/account/access'
      preLoaderRoute: typeof ApiStorefrontAccountAccessRouteImport
      parentRoute: typeof ApiStorefrontAccountRoute
    }
    '/api/documents/quick-expense/$id': {
      id: '/api/documents/quick-expense/$id'
      path: '/api/documents/quick-expense/$id'
      fullPath: '/api/documents/quick-expense/$id'
      preLoaderRoute: typeof ApiDocumentsQuickExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/pos-receipt/$id': {
      id: '/api/documents/pos-receipt/$id'
      path: '/api/documents/pos-receipt/$id'
      fullPath: '/api/documents/pos-receipt/$id'
      preLoaderRoute: typeof ApiDocumentsPosReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/invoice/$id': {
      id: '/api/documents/invoice/$id'
      path: '/api/documents/invoice/$id'
      fullPath: '/api/documents/invoice/$id'
      preLoaderRoute: typeof ApiDocumentsInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/customer-statement/$customerId': {
      id: '/api/documents/customer-statement/$customerId'
      path: '/api/documents/customer-statement/$customerId'
      fullPath: '/api/documents/customer-statement/$customerId'
      preLoaderRoute: typeof ApiDocumentsCustomerStatementCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/credit-note/$id': {
      id: '/api/documents/credit-note/$id'
      path: '/api/documents/credit-note/$id'
      fullPath: '/api/documents/credit-note/$id'
      preLoaderRoute: typeof ApiDocumentsCreditNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/cash-session/$id': {
      id: '/api/documents/cash-session/$id'
      path: '/api/documents/cash-session/$id'
      fullPath: '/api/documents/cash-session/$id'
      preLoaderRoute: typeof ApiDocumentsCashSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/bill/$id': {
      id: '/api/documents/bill/$id'
      path: '/api/documents/bill/$id'
      fullPath: '/api/documents/bill/$id'
      preLoaderRoute: typeof ApiDocumentsBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communications/webhooks/resend': {
      id: '/api/communications/webhooks/resend'
      path: '/api/communications/webhooks/resend'
      fullPath: '/api/communications/webhooks/resend'
      preLoaderRoute: typeof ApiCommunicationsWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront/payments/webhooks/stripe': {
      id: '/api/storefront/payments/webhooks/stripe'
      path: '/api/storefront/payments/webhooks/stripe'
      fullPath: '/api/storefront/payments/webhooks/stripe'
      preLoaderRoute: typeof ApiStorefrontPaymentsWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBillsRouteChildren {
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
}

const AuthenticatedBillsRouteChildren: AuthenticatedBillsRouteChildren = {
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
}

const AuthenticatedBillsRouteWithChildren =
  AuthenticatedBillsRoute._addFileChildren(AuthenticatedBillsRouteChildren)

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedInventoryRouteChildren {
  AuthenticatedInventoryProductIdRoute: typeof AuthenticatedInventoryProductIdRoute
}

const AuthenticatedInventoryRouteChildren: AuthenticatedInventoryRouteChildren =
  {
    AuthenticatedInventoryProductIdRoute: AuthenticatedInventoryProductIdRoute,
  }

const AuthenticatedInventoryRouteWithChildren =
  AuthenticatedInventoryRoute._addFileChildren(
    AuthenticatedInventoryRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedPosOrdersRouteChildren {
  AuthenticatedPosOrdersOrderIdRoute: typeof AuthenticatedPosOrdersOrderIdRoute
}

const AuthenticatedPosOrdersRouteChildren: AuthenticatedPosOrdersRouteChildren =
  {
    AuthenticatedPosOrdersOrderIdRoute: AuthenticatedPosOrdersOrderIdRoute,
  }

const AuthenticatedPosOrdersRouteWithChildren =
  AuthenticatedPosOrdersRoute._addFileChildren(
    AuthenticatedPosOrdersRouteChildren,
  )

interface AuthenticatedQuickExpensesRouteChildren {
  AuthenticatedQuickExpensesExpenseIdRoute: typeof AuthenticatedQuickExpensesExpenseIdRoute
}

const AuthenticatedQuickExpensesRouteChildren: AuthenticatedQuickExpensesRouteChildren =
  {
    AuthenticatedQuickExpensesExpenseIdRoute:
      AuthenticatedQuickExpensesExpenseIdRoute,
  }

const AuthenticatedQuickExpensesRouteWithChildren =
  AuthenticatedQuickExpensesRoute._addFileChildren(
    AuthenticatedQuickExpensesRouteChildren,
  )

interface AuthenticatedRefundsRouteChildren {
  AuthenticatedRefundsCreditNoteIdRoute: typeof AuthenticatedRefundsCreditNoteIdRoute
}

const AuthenticatedRefundsRouteChildren: AuthenticatedRefundsRouteChildren = {
  AuthenticatedRefundsCreditNoteIdRoute: AuthenticatedRefundsCreditNoteIdRoute,
}

const AuthenticatedRefundsRouteWithChildren =
  AuthenticatedRefundsRoute._addFileChildren(AuthenticatedRefundsRouteChildren)

interface AuthenticatedSalesRouteChildren {
  AuthenticatedSalesOrderIdRoute: typeof AuthenticatedSalesOrderIdRoute
}

const AuthenticatedSalesRouteChildren: AuthenticatedSalesRouteChildren = {
  AuthenticatedSalesOrderIdRoute: AuthenticatedSalesOrderIdRoute,
}

const AuthenticatedSalesRouteWithChildren =
  AuthenticatedSalesRoute._addFileChildren(AuthenticatedSalesRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBranchesRoute: typeof AuthenticatedSettingsBranchesRoute
  AuthenticatedSettingsCollectionsRoute: typeof AuthenticatedSettingsCollectionsRoute
  AuthenticatedSettingsDocumentTemplatesRoute: typeof AuthenticatedSettingsDocumentTemplatesRoute
  AuthenticatedSettingsModulesRoute: typeof AuthenticatedSettingsModulesRoute
  AuthenticatedSettingsTaxRatesRoute: typeof AuthenticatedSettingsTaxRatesRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBranchesRoute: AuthenticatedSettingsBranchesRoute,
  AuthenticatedSettingsCollectionsRoute: AuthenticatedSettingsCollectionsRoute,
  AuthenticatedSettingsDocumentTemplatesRoute:
    AuthenticatedSettingsDocumentTemplatesRoute,
  AuthenticatedSettingsModulesRoute: AuthenticatedSettingsModulesRoute,
  AuthenticatedSettingsTaxRatesRoute: AuthenticatedSettingsTaxRatesRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedStoreRouteChildren {
  AuthenticatedStoreOrderIdRoute: typeof AuthenticatedStoreOrderIdRoute
  AuthenticatedStoreDesignRoute: typeof AuthenticatedStoreDesignRoute
  AuthenticatedStoreSetupRoute: typeof AuthenticatedStoreSetupRoute
}

const AuthenticatedStoreRouteChildren: AuthenticatedStoreRouteChildren = {
  AuthenticatedStoreOrderIdRoute: AuthenticatedStoreOrderIdRoute,
  AuthenticatedStoreDesignRoute: AuthenticatedStoreDesignRoute,
  AuthenticatedStoreSetupRoute: AuthenticatedStoreSetupRoute,
}

const AuthenticatedStoreRouteWithChildren =
  AuthenticatedStoreRoute._addFileChildren(AuthenticatedStoreRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRouteWithChildren
  AuthenticatedCashSessionsRoute: typeof AuthenticatedCashSessionsRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRouteWithChildren
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedPosOrdersRoute: typeof AuthenticatedPosOrdersRouteWithChildren
  AuthenticatedQuickExpensesRoute: typeof AuthenticatedQuickExpensesRouteWithChildren
  AuthenticatedRefundsRoute: typeof AuthenticatedRefundsRouteWithChildren
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedAccountingCoaRoute: typeof AuthenticatedAccountingCoaRoute
  AuthenticatedAccountingControlsRoute: typeof AuthenticatedAccountingControlsRoute
  AuthenticatedReportsBalanceSheetRoute: typeof AuthenticatedReportsBalanceSheetRoute
  AuthenticatedReportsCashFlowRoute: typeof AuthenticatedReportsCashFlowRoute
  AuthenticatedReportsLedgerRoute: typeof AuthenticatedReportsLedgerRoute
  AuthenticatedReportsProfitLossRoute: typeof AuthenticatedReportsProfitLossRoute
  AuthenticatedReportsSalesRoute: typeof AuthenticatedReportsSalesRoute
  AuthenticatedReportsTaxRoute: typeof AuthenticatedReportsTaxRoute
  AuthenticatedReportsTrialBalanceRoute: typeof AuthenticatedReportsTrialBalanceRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillsRoute: AuthenticatedBillsRouteWithChildren,
  AuthenticatedCashSessionsRoute: AuthenticatedCashSessionsRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRouteWithChildren,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedPosOrdersRoute: AuthenticatedPosOrdersRouteWithChildren,
  AuthenticatedQuickExpensesRoute: AuthenticatedQuickExpensesRouteWithChildren,
  AuthenticatedRefundsRoute: AuthenticatedRefundsRouteWithChildren,
  AuthenticatedSalesRoute: AuthenticatedSalesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStoreRoute: AuthenticatedStoreRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedAccountingCoaRoute: AuthenticatedAccountingCoaRoute,
  AuthenticatedAccountingControlsRoute: AuthenticatedAccountingControlsRoute,
  AuthenticatedReportsBalanceSheetRoute: AuthenticatedReportsBalanceSheetRoute,
  AuthenticatedReportsCashFlowRoute: AuthenticatedReportsCashFlowRoute,
  AuthenticatedReportsLedgerRoute: AuthenticatedReportsLedgerRoute,
  AuthenticatedReportsProfitLossRoute: AuthenticatedReportsProfitLossRoute,
  AuthenticatedReportsSalesRoute: AuthenticatedReportsSalesRoute,
  AuthenticatedReportsTaxRoute: AuthenticatedReportsTaxRoute,
  AuthenticatedReportsTrialBalanceRoute: AuthenticatedReportsTrialBalanceRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ShopStoreSlugAccountRouteChildren {
  ShopStoreSlugAccountAccessRoute: typeof ShopStoreSlugAccountAccessRoute
}

const ShopStoreSlugAccountRouteChildren: ShopStoreSlugAccountRouteChildren = {
  ShopStoreSlugAccountAccessRoute: ShopStoreSlugAccountAccessRoute,
}

const ShopStoreSlugAccountRouteWithChildren =
  ShopStoreSlugAccountRoute._addFileChildren(ShopStoreSlugAccountRouteChildren)

interface ShopStoreSlugRouteChildren {
  ShopStoreSlugAccountRoute: typeof ShopStoreSlugAccountRouteWithChildren
  ShopStoreSlugCartRoute: typeof ShopStoreSlugCartRoute
  ShopStoreSlugCheckoutRoute: typeof ShopStoreSlugCheckoutRoute
  ShopStoreSlugIndexRoute: typeof ShopStoreSlugIndexRoute
  ShopStoreSlugCategoryCategoryKeyRoute: typeof ShopStoreSlugCategoryCategoryKeyRoute
  ShopStoreSlugOrderOrderIdRoute: typeof ShopStoreSlugOrderOrderIdRoute
  ShopStoreSlugProductProductKeyRoute: typeof ShopStoreSlugProductProductKeyRoute
}

const ShopStoreSlugRouteChildren: ShopStoreSlugRouteChildren = {
  ShopStoreSlugAccountRoute: ShopStoreSlugAccountRouteWithChildren,
  ShopStoreSlugCartRoute: ShopStoreSlugCartRoute,
  ShopStoreSlugCheckoutRoute: ShopStoreSlugCheckoutRoute,
  ShopStoreSlugIndexRoute: ShopStoreSlugIndexRoute,
  ShopStoreSlugCategoryCategoryKeyRoute: ShopStoreSlugCategoryCategoryKeyRoute,
  ShopStoreSlugOrderOrderIdRoute: ShopStoreSlugOrderOrderIdRoute,
  ShopStoreSlugProductProductKeyRoute: ShopStoreSlugProductProductKeyRoute,
}

const ShopStoreSlugRouteWithChildren = ShopStoreSlugRoute._addFileChildren(
  ShopStoreSlugRouteChildren,
)

interface ApiStorefrontAccountRouteChildren {
  ApiStorefrontAccountAccessRoute: typeof ApiStorefrontAccountAccessRoute
  ApiStorefrontAccountDocumentRoute: typeof ApiStorefrontAccountDocumentRoute
  ApiStorefrontAccountOrderRoute: typeof ApiStorefrontAccountOrderRoute
  ApiStorefrontAccountPayInvoiceRoute: typeof ApiStorefrontAccountPayInvoiceRoute
  ApiStorefrontAccountRetryPaymentRoute: typeof ApiStorefrontAccountRetryPaymentRoute
}

const ApiStorefrontAccountRouteChildren: ApiStorefrontAccountRouteChildren = {
  ApiStorefrontAccountAccessRoute: ApiStorefrontAccountAccessRoute,
  ApiStorefrontAccountDocumentRoute: ApiStorefrontAccountDocumentRoute,
  ApiStorefrontAccountOrderRoute: ApiStorefrontAccountOrderRoute,
  ApiStorefrontAccountPayInvoiceRoute: ApiStorefrontAccountPayInvoiceRoute,
  ApiStorefrontAccountRetryPaymentRoute: ApiStorefrontAccountRetryPaymentRoute,
}

const ApiStorefrontAccountRouteWithChildren =
  ApiStorefrontAccountRoute._addFileChildren(ApiStorefrontAccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ShopStoreSlugRoute: ShopStoreSlugRouteWithChildren,
  ApiCollectionsDashboardRoute: ApiCollectionsDashboardRoute,
  ApiCommunicationsBatchPreviewRoute: ApiCommunicationsBatchPreviewRoute,
  ApiCommunicationsBatchSendRoute: ApiCommunicationsBatchSendRoute,
  ApiCommunicationsProcessQueueRoute: ApiCommunicationsProcessQueueRoute,
  ApiCommunicationsRetryRoute: ApiCommunicationsRetryRoute,
  ApiCommunicationsRunScheduledRoute: ApiCommunicationsRunScheduledRoute,
  ApiCommunicationsSendRoute: ApiCommunicationsSendRoute,
  ApiStorefrontAccountRoute: ApiStorefrontAccountRouteWithChildren,
  ApiStorefrontCatalogRoute: ApiStorefrontCatalogRoute,
  ApiStorefrontCheckoutRoute: ApiStorefrontCheckoutRoute,
  ApiStorefrontCheckoutContextRoute: ApiStorefrontCheckoutContextRoute,
  ApiStorefrontDesignRoute: ApiStorefrontDesignRoute,
  ApiStorefrontPreviewRoute: ApiStorefrontPreviewRoute,
  ApiStorefrontProductRoute: ApiStorefrontProductRoute,
  ApiStorefrontSetupRoute: ApiStorefrontSetupRoute,
  ApiCommunicationsWebhooksResendRoute: ApiCommunicationsWebhooksResendRoute,
  ApiDocumentsBillIdRoute: ApiDocumentsBillIdRoute,
  ApiDocumentsCashSessionIdRoute: ApiDocumentsCashSessionIdRoute,
  ApiDocumentsCreditNoteIdRoute: ApiDocumentsCreditNoteIdRoute,
  ApiDocumentsCustomerStatementCustomerIdRoute:
    ApiDocumentsCustomerStatementCustomerIdRoute,
  ApiDocumentsInvoiceIdRoute: ApiDocumentsInvoiceIdRoute,
  ApiDocumentsPosReceiptIdRoute: ApiDocumentsPosReceiptIdRoute,
  ApiDocumentsQuickExpenseIdRoute: ApiDocumentsQuickExpenseIdRoute,
  ApiStorefrontPaymentsWebhooksStripeRoute:
    ApiStorefrontPaymentsWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
