/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated.suppliers'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated.store'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated.sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedRefundsRouteImport } from './routes/_authenticated.refunds'
import { Route as AuthenticatedQuickExpensesRouteImport } from './routes/_authenticated.quick-expenses'
import { Route as AuthenticatedPosOrdersRouteImport } from './routes/_authenticated.pos-orders'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated.pos'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated.payments'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated.invoices'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated.inventory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated.customers'
import { Route as AuthenticatedCashSessionsRouteImport } from './routes/_authenticated.cash-sessions'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated.bills'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedStoreOrderIdRouteImport } from './routes/_authenticated.store.$orderId'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated.settings.users'
import { Route as AuthenticatedSettingsTaxRatesRouteImport } from './routes/_authenticated.settings.tax-rates'
import { Route as AuthenticatedSettingsModulesRouteImport } from './routes/_authenticated.settings.modules'
import { Route as AuthenticatedSettingsBranchesRouteImport } from './routes/_authenticated.settings.branches'
import { Route as AuthenticatedSalesOrderIdRouteImport } from './routes/_authenticated.sales.$orderId'
import { Route as AuthenticatedRefundsCreditNoteIdRouteImport } from './routes/_authenticated.refunds.$creditNoteId'
import { Route as AuthenticatedQuickExpensesExpenseIdRouteImport } from './routes/_authenticated.quick-expenses.$expenseId'
import { Route as AuthenticatedPosOrdersOrderIdRouteImport } from './routes/_authenticated.pos-orders.$orderId'
import { Route as AuthenticatedInventoryProductIdRouteImport } from './routes/_authenticated.inventory.$productId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated.customers.$customerId'
import { Route as AuthenticatedAccountingCoaRouteImport } from './routes/_authenticated.accounting.coa'
import { Route as ApiDocumentsPosReceiptIdRouteImport } from './routes/api.documents.pos-receipt.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRefundsRoute = AuthenticatedRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuickExpensesRoute =
  AuthenticatedQuickExpensesRouteImport.update({
    id: '/quick-expenses',
    path: '/quick-expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPosOrdersRoute = AuthenticatedPosOrdersRouteImport.update({
  id: '/pos-orders',
  path: '/pos-orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCashSessionsRoute =
  AuthenticatedCashSessionsRouteImport.update({
    id: '/cash-sessions',
    path: '/cash-sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedStoreOrderIdRoute =
  AuthenticatedStoreOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedStoreRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTaxRatesRoute =
  AuthenticatedSettingsTaxRatesRouteImport.update({
    id: '/tax-rates',
    path: '/tax-rates',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsModulesRoute =
  AuthenticatedSettingsModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBranchesRoute =
  AuthenticatedSettingsBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSalesOrderIdRoute =
  AuthenticatedSalesOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedSalesRoute,
  } as any)
const AuthenticatedRefundsCreditNoteIdRoute =
  AuthenticatedRefundsCreditNoteIdRouteImport.update({
    id: '/$creditNoteId',
    path: '/$creditNoteId',
    getParentRoute: () => AuthenticatedRefundsRoute,
  } as any)
const AuthenticatedQuickExpensesExpenseIdRoute =
  AuthenticatedQuickExpensesExpenseIdRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => AuthenticatedQuickExpensesRoute,
  } as any)
const AuthenticatedPosOrdersOrderIdRoute =
  AuthenticatedPosOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedPosOrdersRoute,
  } as any)
const AuthenticatedInventoryProductIdRoute =
  AuthenticatedInventoryProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedAccountingCoaRoute =
  AuthenticatedAccountingCoaRouteImport.update({
    id: '/accounting/coa',
    path: '/accounting/coa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiDocumentsPosReceiptIdRoute =
  ApiDocumentsPosReceiptIdRouteImport.update({
    id: '/api/documents/pos-receipt/$id',
    path: '/api/documents/pos-receipt/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pos-orders': typeof AuthenticatedPosOrdersRouteWithChildren
  '/quick-expenses': typeof AuthenticatedQuickExpensesRouteWithChildren
  '/refunds': typeof AuthenticatedRefundsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/store': typeof AuthenticatedStoreRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/accounting/coa': typeof AuthenticatedAccountingCoaRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/inventory/$productId': typeof AuthenticatedInventoryProductIdRoute
  '/pos-orders/$orderId': typeof AuthenticatedPosOrdersOrderIdRoute
  '/quick-expenses/$expenseId': typeof AuthenticatedQuickExpensesExpenseIdRoute
  '/refunds/$creditNoteId': typeof AuthenticatedRefundsCreditNoteIdRoute
  '/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/store/$orderId': typeof AuthenticatedStoreOrderIdRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/documents/pos-receipt/$id': typeof ApiDocumentsPosReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/pos-orders': typeof AuthenticatedPosOrdersRouteWithChildren
  '/quick-expenses': typeof AuthenticatedQuickExpensesRouteWithChildren
  '/refunds': typeof AuthenticatedRefundsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/store': typeof AuthenticatedStoreRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/accounting/coa': typeof AuthenticatedAccountingCoaRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/inventory/$productId': typeof AuthenticatedInventoryProductIdRoute
  '/pos-orders/$orderId': typeof AuthenticatedPosOrdersOrderIdRoute
  '/quick-expenses/$expenseId': typeof AuthenticatedQuickExpensesExpenseIdRoute
  '/refunds/$creditNoteId': typeof AuthenticatedRefundsCreditNoteIdRoute
  '/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/store/$orderId': typeof AuthenticatedStoreOrderIdRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/documents/pos-receipt/$id': typeof ApiDocumentsPosReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRoute
  '/_authenticated/cash-sessions': typeof AuthenticatedCashSessionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/pos-orders': typeof AuthenticatedPosOrdersRouteWithChildren
  '/_authenticated/quick-expenses': typeof AuthenticatedQuickExpensesRouteWithChildren
  '/_authenticated/refunds': typeof AuthenticatedRefundsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/store': typeof AuthenticatedStoreRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/accounting/coa': typeof AuthenticatedAccountingCoaRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/inventory/$productId': typeof AuthenticatedInventoryProductIdRoute
  '/_authenticated/pos-orders/$orderId': typeof AuthenticatedPosOrdersOrderIdRoute
  '/_authenticated/quick-expenses/$expenseId': typeof AuthenticatedQuickExpensesExpenseIdRoute
  '/_authenticated/refunds/$creditNoteId': typeof AuthenticatedRefundsCreditNoteIdRoute
  '/_authenticated/sales/$orderId': typeof AuthenticatedSalesOrderIdRoute
  '/_authenticated/settings/branches': typeof AuthenticatedSettingsBranchesRoute
  '/_authenticated/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/_authenticated/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/store/$orderId': typeof AuthenticatedStoreOrderIdRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/documents/pos-receipt/$id': typeof ApiDocumentsPosReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/bills'
    | '/cash-sessions'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/invoices'
    | '/payments'
    | '/pos'
    | '/pos-orders'
    | '/quick-expenses'
    | '/refunds'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/store'
    | '/suppliers'
    | '/accounting/coa'
    | '/customers/$customerId'
    | '/inventory/$productId'
    | '/pos-orders/$orderId'
    | '/quick-expenses/$expenseId'
    | '/refunds/$creditNoteId'
    | '/sales/$orderId'
    | '/settings/branches'
    | '/settings/modules'
    | '/settings/tax-rates'
    | '/settings/users'
    | '/store/$orderId'
    | '/settings/'
    | '/api/documents/pos-receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/bills'
    | '/cash-sessions'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/invoices'
    | '/payments'
    | '/pos'
    | '/pos-orders'
    | '/quick-expenses'
    | '/refunds'
    | '/reports'
    | '/sales'
    | '/store'
    | '/suppliers'
    | '/accounting/coa'
    | '/customers/$customerId'
    | '/inventory/$productId'
    | '/pos-orders/$orderId'
    | '/quick-expenses/$expenseId'
    | '/refunds/$creditNoteId'
    | '/sales/$orderId'
    | '/settings/branches'
    | '/settings/modules'
    | '/settings/tax-rates'
    | '/settings/users'
    | '/store/$orderId'
    | '/settings'
    | '/api/documents/pos-receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/bills'
    | '/_authenticated/cash-sessions'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/payments'
    | '/_authenticated/pos'
    | '/_authenticated/pos-orders'
    | '/_authenticated/quick-expenses'
    | '/_authenticated/refunds'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/store'
    | '/_authenticated/suppliers'
    | '/_authenticated/accounting/coa'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/inventory/$productId'
    | '/_authenticated/pos-orders/$orderId'
    | '/_authenticated/quick-expenses/$expenseId'
    | '/_authenticated/refunds/$creditNoteId'
    | '/_authenticated/sales/$orderId'
    | '/_authenticated/settings/branches'
    | '/_authenticated/settings/modules'
    | '/_authenticated/settings/tax-rates'
    | '/_authenticated/settings/users'
    | '/_authenticated/store/$orderId'
    | '/_authenticated/settings/'
    | '/api/documents/pos-receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiDocumentsPosReceiptIdRoute: typeof ApiDocumentsPosReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refunds': {
      id: '/_authenticated/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof AuthenticatedRefundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quick-expenses': {
      id: '/_authenticated/quick-expenses'
      path: '/quick-expenses'
      fullPath: '/quick-expenses'
      preLoaderRoute: typeof AuthenticatedQuickExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos-orders': {
      id: '/_authenticated/pos-orders'
      path: '/pos-orders'
      fullPath: '/pos-orders'
      preLoaderRoute: typeof AuthenticatedPosOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cash-sessions': {
      id: '/_authenticated/cash-sessions'
      path: '/cash-sessions'
      fullPath: '/cash-sessions'
      preLoaderRoute: typeof AuthenticatedCashSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/store/$orderId': {
      id: '/_authenticated/store/$orderId'
      path: '/$orderId'
      fullPath: '/store/$orderId'
      preLoaderRoute: typeof AuthenticatedStoreOrderIdRouteImport
      parentRoute: typeof AuthenticatedStoreRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/tax-rates': {
      id: '/_authenticated/settings/tax-rates'
      path: '/tax-rates'
      fullPath: '/settings/tax-rates'
      preLoaderRoute: typeof AuthenticatedSettingsTaxRatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/modules': {
      id: '/_authenticated/settings/modules'
      path: '/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AuthenticatedSettingsModulesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/branches': {
      id: '/_authenticated/settings/branches'
      path: '/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof AuthenticatedSettingsBranchesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/sales/$orderId': {
      id: '/_authenticated/sales/$orderId'
      path: '/$orderId'
      fullPath: '/sales/$orderId'
      preLoaderRoute: typeof AuthenticatedSalesOrderIdRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/refunds/$creditNoteId': {
      id: '/_authenticated/refunds/$creditNoteId'
      path: '/$creditNoteId'
      fullPath: '/refunds/$creditNoteId'
      preLoaderRoute: typeof AuthenticatedRefundsCreditNoteIdRouteImport
      parentRoute: typeof AuthenticatedRefundsRoute
    }
    '/_authenticated/quick-expenses/$expenseId': {
      id: '/_authenticated/quick-expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/quick-expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedQuickExpensesExpenseIdRouteImport
      parentRoute: typeof AuthenticatedQuickExpensesRoute
    }
    '/_authenticated/pos-orders/$orderId': {
      id: '/_authenticated/pos-orders/$orderId'
      path: '/$orderId'
      fullPath: '/pos-orders/$orderId'
      preLoaderRoute: typeof AuthenticatedPosOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedPosOrdersRoute
    }
    '/_authenticated/inventory/$productId': {
      id: '/_authenticated/inventory/$productId'
      path: '/$productId'
      fullPath: '/inventory/$productId'
      preLoaderRoute: typeof AuthenticatedInventoryProductIdRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/accounting/coa': {
      id: '/_authenticated/accounting/coa'
      path: '/accounting/coa'
      fullPath: '/accounting/coa'
      preLoaderRoute: typeof AuthenticatedAccountingCoaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/documents/pos-receipt/$id': {
      id: '/api/documents/pos-receipt/$id'
      path: '/api/documents/pos-receipt/$id'
      fullPath: '/api/documents/pos-receipt/$id'
      preLoaderRoute: typeof ApiDocumentsPosReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedInventoryRouteChildren {
  AuthenticatedInventoryProductIdRoute: typeof AuthenticatedInventoryProductIdRoute
}

const AuthenticatedInventoryRouteChildren: AuthenticatedInventoryRouteChildren =
  {
    AuthenticatedInventoryProductIdRoute: AuthenticatedInventoryProductIdRoute,
  }

const AuthenticatedInventoryRouteWithChildren =
  AuthenticatedInventoryRoute._addFileChildren(
    AuthenticatedInventoryRouteChildren,
  )

interface AuthenticatedPosOrdersRouteChildren {
  AuthenticatedPosOrdersOrderIdRoute: typeof AuthenticatedPosOrdersOrderIdRoute
}

const AuthenticatedPosOrdersRouteChildren: AuthenticatedPosOrdersRouteChildren =
  {
    AuthenticatedPosOrdersOrderIdRoute: AuthenticatedPosOrdersOrderIdRoute,
  }

const AuthenticatedPosOrdersRouteWithChildren =
  AuthenticatedPosOrdersRoute._addFileChildren(
    AuthenticatedPosOrdersRouteChildren,
  )

interface AuthenticatedQuickExpensesRouteChildren {
  AuthenticatedQuickExpensesExpenseIdRoute: typeof AuthenticatedQuickExpensesExpenseIdRoute
}

const AuthenticatedQuickExpensesRouteChildren: AuthenticatedQuickExpensesRouteChildren =
  {
    AuthenticatedQuickExpensesExpenseIdRoute:
      AuthenticatedQuickExpensesExpenseIdRoute,
  }

const AuthenticatedQuickExpensesRouteWithChildren =
  AuthenticatedQuickExpensesRoute._addFileChildren(
    AuthenticatedQuickExpensesRouteChildren,
  )

interface AuthenticatedRefundsRouteChildren {
  AuthenticatedRefundsCreditNoteIdRoute: typeof AuthenticatedRefundsCreditNoteIdRoute
}

const AuthenticatedRefundsRouteChildren: AuthenticatedRefundsRouteChildren = {
  AuthenticatedRefundsCreditNoteIdRoute: AuthenticatedRefundsCreditNoteIdRoute,
}

const AuthenticatedRefundsRouteWithChildren =
  AuthenticatedRefundsRoute._addFileChildren(AuthenticatedRefundsRouteChildren)

interface AuthenticatedSalesRouteChildren {
  AuthenticatedSalesOrderIdRoute: typeof AuthenticatedSalesOrderIdRoute
}

const AuthenticatedSalesRouteChildren: AuthenticatedSalesRouteChildren = {
  AuthenticatedSalesOrderIdRoute: AuthenticatedSalesOrderIdRoute,
}

const AuthenticatedSalesRouteWithChildren =
  AuthenticatedSalesRoute._addFileChildren(AuthenticatedSalesRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBranchesRoute: typeof AuthenticatedSettingsBranchesRoute
  AuthenticatedSettingsModulesRoute: typeof AuthenticatedSettingsModulesRoute
  AuthenticatedSettingsTaxRatesRoute: typeof AuthenticatedSettingsTaxRatesRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBranchesRoute: AuthenticatedSettingsBranchesRoute,
  AuthenticatedSettingsModulesRoute: AuthenticatedSettingsModulesRoute,
  AuthenticatedSettingsTaxRatesRoute: AuthenticatedSettingsTaxRatesRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedStoreRouteChildren {
  AuthenticatedStoreOrderIdRoute: typeof AuthenticatedStoreOrderIdRoute
}

const AuthenticatedStoreRouteChildren: AuthenticatedStoreRouteChildren = {
  AuthenticatedStoreOrderIdRoute: AuthenticatedStoreOrderIdRoute,
}

const AuthenticatedStoreRouteWithChildren =
  AuthenticatedStoreRoute._addFileChildren(AuthenticatedStoreRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRoute
  AuthenticatedCashSessionsRoute: typeof AuthenticatedCashSessionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRouteWithChildren
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedPosOrdersRoute: typeof AuthenticatedPosOrdersRouteWithChildren
  AuthenticatedQuickExpensesRoute: typeof AuthenticatedQuickExpensesRouteWithChildren
  AuthenticatedRefundsRoute: typeof AuthenticatedRefundsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedAccountingCoaRoute: typeof AuthenticatedAccountingCoaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillsRoute: AuthenticatedBillsRoute,
  AuthenticatedCashSessionsRoute: AuthenticatedCashSessionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRouteWithChildren,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedPosOrdersRoute: AuthenticatedPosOrdersRouteWithChildren,
  AuthenticatedQuickExpensesRoute: AuthenticatedQuickExpensesRouteWithChildren,
  AuthenticatedRefundsRoute: AuthenticatedRefundsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStoreRoute: AuthenticatedStoreRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedAccountingCoaRoute: AuthenticatedAccountingCoaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiDocumentsPosReceiptIdRoute: ApiDocumentsPosReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
